services:
  mongo:
    image: mongo:7.0.9-jammy
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    ports:
      - '5050:5050'
    volumes:
      - ./backend:/app
      - /app/node_modules  # Prevent node_modules being overwritten
    environment:
      - NODE_ENV=development
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - '80:80'
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Prevent node_modules being overwritten
    environment:
      - NODE_ENV=development

volumes:
  mongo-data:
