version: '3.8'

services:
  mongodb:
    image: mongo:7.0.9-jammy
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - mern_network
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5050:5050"
    networks:
      - mern_network
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mydatabase
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - mern_network
    environment:
      - REACT_APP_API_URL=http://backend:5050

networks:
  mern_network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
