name: Build MERN app

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize]

jobs:
  Build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout SCM
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Cache Node modules (Frontend)
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-frontend-${{ hashFiles('mern/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-frontend-

      # Frontend
      - name: Install frontend dependencies
        run: |
          cd mern/frontend
          npm install

      - name: Run frontend lint and tests
        run: |
          cd mern/frontend
          npm run lint
          npm run test

      - name: Build frontend
        run: |
          cd mern/frontend
          npm run build

      - name: Upload frontend build
        uses: actions/upload-artifact@v3
        with:
          name: frontend-dist
          path: mern/frontend/dist

      # Backend
      - name: Cache Node modules (Backend)
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-backend-${{ hashFiles('mern/backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-backend-

      - name: Install backend dependencies
        run: |
          cd mern/backend
          npm install

      - name: Run backend lint
        run: |
          cd mern/backend
          npm run lint
          
      - name: Run backend tests
        run: |
          cd mern/backend
          npm run test -- --passWithNoTests

      - name: Upload backend build
        uses: actions/upload-artifact@v3
        with:
          name: backend-output
          path: mern/backend/build

      # Docker Setup
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build frontend Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/react-app:${{ github.sha }} mern/frontend

      - name: Build backend Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/node-backend:${{ github.sha }} mern/backend
