name: Build MERN app
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
    types: [opened, synchronize]
jobs:
  Build:
    runs-on: ubuntu-22.04
    services:
      mongodb: # MongoDB for tests
        image: bitnami/mongodb:6.0
        ports:
          - 27017:27017
    steps:
      - name: Checkout SCM
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Cache Node modules
        id: cache-node-backend
        uses: actions/cache@v3
        with:
          path: mern/backend/.npm
          key: ${{ runner.os }}-backend-node-modules-${{ hashFiles('mern/backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-backend-node-modules-
        # Speeds up npm install
      - name: Install backend dependencies
        if: steps.cache-node-backend.outputs.cache-hit != 'true'
        run: |
          cd mern/backend
          npm install --verbose || { echo "Backend npm install failed"; exit 1; }

      - name: Run backend lint
        run: |
          cd mern/backend
          npm run lint || { echo "Backend lint failed"; exit 1; }
        # Checks code with .eslintrc.cjs or eslint.config.js
      - name: Run backend tests
        run: |
          cd mern/backend
          npm run test || { echo "Backend tests failed"; exit 1; }

      - name: Cache frontend node_modules
        id: cache-node-frontend
        uses: actions/cache@v3
        with:
          path: mern/frontend/.npm
          key: ${{ runner.os }}-frontend-node-modules-${{ hashFiles('mern/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-frontend-node-modules-

      - name: Install frontend dependencies
        if: steps.cache-node-frontend.outputs.cache-hit != 'true'
        run: |
          cd mern/frontend
          npm install --verbose || { echo "Frontend npm install failed"; exit 1; }

      - name: Run frontend lint
        run: |
          cd mern/frontend
          npm run lint || { echo "Frontend lint failed"; exit 1; }

      - name: Run frontend tests
        run: |
          cd mern/frontend
          npm run test || { echo "Frontend tests failed"; exit 1; }

        # Runs Jest tests
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
  
      - name: Build backend Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME}}/mern-backend:${{ github.sha }} mern/backend
        # Builds Docker image
      - name: Build frontend Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME}}/mern-frontend:${{ github.sha }} mern/frontend
