name: Build MERN app
on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - main
    types: [opened, synchronize]
jobs:
  Build:
    runs-on: ubuntu-22.04
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
    steps:
      - name: Checkout SCM
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Cache Node modules (Frontend)
        uses: actions/cache@v3
        with:
          path: mern/frontend/node_modules
          key: ${{ runner.os }}-frontend-${{ hashFiles('mern/frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-frontend-
      - name: Install frontend dependencies
        run: |
          cd mern/frontend
          npm install --verbose || { echo "Frontend npm install failed"; exit 1; }
      - name: Run frontend lint and tests
        run: |
          cd mern/frontend
          npm run lint || { echo "Frontend lint failed"; exit 1; }
          npm run test || { echo "Frontend tests failed"; exit 1; }
      - name: Build frontend
        run: |
          cd mern/frontend
          npm run build || { echo "Frontend build failed"; exit 1; }
      - name: Upload frontend build
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: mern/frontend/dist
      - name: Cache Node modules (Backend)
        uses: actions/cache@v3
        with:
          path: mern/backend/node_modules
          key: ${{ runner.os }}-backend-${{ hashFiles('mern/backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-backend-
      - name: Install backend dependencies
        run: |
          cd mern/backend
          npm install --verbose || { echo "Backend npm install failed"; exit 1; }
      - name: Run backend lint
        run: |
          cd mern/backend
          npm run lint || { echo "Backend lint failed"; exit 1; }
      - name: Run backend tests
        run: |
          cd mern/backend
          npm run test || { echo "Backend tests failed"; exit 1; }
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Create Docker network
        run: docker network create demo || true
      - name: Build frontend Docker image
        run: |
          docker build -t mern-frontend:${{ github.sha }} mern/frontend
      - name: Build backend Docker image
        run: |
          docker build -t mern-backend:${{ github.sha }} mern/backend