name: Deploy MERN App

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  deploy:
    runs-on: ubuntu-22.04
    if: github.event.pull_request.merged == true
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Configure Kubernetes Access
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.32.2

      - name: Configure KUBECONFIG
        run: |
            mkdir -p $HOME/.kube
            echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config
            chmod 600 $HOME/.kube/config


      # Create Docker registry secret (regcred)
      - name: Create regcred Docker secret
        run: |
          kubectl create secret docker-registry regcred \
            --docker-server=https://index.docker.io/v1/ \
            --docker-username=${{ secrets.DOCKER_USERNAME }} \
            --docker-password=${{ secrets.DOCKER_PASSWORD }} \
            --dry-run=client -o yaml | kubectl apply -f -

      # Create MongoDB secret
      - name: Create backend app secret
        run: |
          kubectl create secret generic backend-secrets \
            --from-literal=MONGODB_URI=${{ secrets.MONGODB_URI }} \
            --dry-run=client -o yaml | kubectl apply -f -

      # Docker Build and Push - Frontend
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend
        uses: docker/build-push-action@v3
        with:
          context: ./mern/frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/frontend:pr-${{ github.event.pull_request.number }}-${{ github.sha }}

      - name: Build and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./mern/backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/node-backend:pr-${{ github.event.pull_request.number }}-${{ github.sha }}

      # Pull Deployment Manifests
      - name: Checkout deployment-manifests repo
        uses: actions/checkout@v3
        with:
          repository: Ajaypratapsingh2018/Deployment-manifests
          token: ${{ secrets.K8S_MANIFEST }}
          path: deployment-manifests

      # Update Image Tags in Deployment YAMLs
      - name: Update image tags
        run: |
          sed -i "s|FRONTEND_IMAGE_TAG_PLACEHOLDER|pr-${{ github.event.pull_request.number }}-${{ github.sha }}|g" deployment-manifests/manifests/frontend-deployment.yml
          sed -i "s|BACKEND_IMAGE_TAG_PLACEHOLDER|pr-${{ github.event.pull_request.number }}-${{ github.sha }}|g" deployment-manifests/manifests/backend-deployment.yml

      # Apply Updated Manifests to AKS
      - name: Apply manifests
        run: |
          kubectl apply -f deployment-manifests/manifests/frontend-deployment.yaml
          kubectl apply -f deployment-manifests/manifests/backend-deployment.yaml
