name: Deploy MERN App

on:
  pull_request:
    branches: [main]
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend
        uses: docker/build-push-action@v3
        with:
          context: ./mern/frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/frontend:pr-${{ github.event.pull_request.number }}-${{ github.sha }}

      - name: Build and push backend
        uses: docker/build-push-action@v3
        with:
          context: ./mern/backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/node-backend:pr-${{ github.event.pull_request.number }}-${{ github.sha }}

  deploy:
    runs-on: ubuntu-22.04
    if: github.event.pull_request.merged == true
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.32.2

      - name: Configure KUBECONFIG
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Create regcred Docker secret
        run: |
          kubectl create secret docker-registry regcred \
            --docker-server=https://index.docker.io/v1/ \
            --docker-username=${{ secrets.DOCKER_USERNAME }} \
            --docker-password=${{ secrets.DOCKER_PASSWORD }} \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Create/Update backend-secrets
        run: |
          kubectl create secret generic backend-secrets \
            --from-literal=MONGODB_URI="${{ secrets.MONGODB_URI }}" \
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Checkout deployment-manifests repo
        uses: actions/checkout@v3
        with:
          repository: Ajaypratapsingh2018/Deployment-manifests
          token: ${{ secrets.K8S_MANIFEST }}
          path: deployment-manifests

      - name: Debug manifest files
        run: |
          ls -R deployment-manifests/manifests
          cat deployment-manifests/manifests/frontend-deployment.yml || echo "frontend-deployment.yml not found"
          cat deployment-manifests/manifests/frontend-svc.yml || echo "frontend-svc.yml not found"
          cat deployment-manifests/manifests/backend-deployment.yml || echo "backend-deployment.yml not found"
          cat deployment-manifests/manifests/backend-svc.yml || echo "backend-svc.yml not found"
          cat deployment-manifests/manifests/mongo-deployment.yml || echo "mongo-deployment.yml not found"

      - name: Update image tags
        run: |
          sed -i -E "s|iamvegetaaj/frontend:pr-[0-9]+-[a-f0-9]+|iamvegetaaj/frontend:pr-${{ github.event.pull_request.number }}-${{ github.sha }}|g" deployment-manifests/manifests/frontend-deployment.yml
          sed -i -E "s|iamvegetaaj/node-backend:pr-[0-9]+-[a-f0-9]+|iamvegetaaj/node-backend:pr-${{ github.event.pull_request.number }}-${{ github.sha }}|g" deployment-manifests/manifests/backend-deployment.yml

      - name: Commit and push updated image tags
        run: |
          cd deployment-manifests
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add manifests/*.yml
          git commit -m "CI: Update image tags for PR #${{ github.event.pull_request.number }}" || echo "No changes to commit"
          git push

      - name: Apply manifests
        run: |
          kubectl apply -f deployment-manifests/manifests/frontend-deployment.yml || { echo "Failed to apply frontend-deployment.yml"; exit 1; }
          kubectl apply -f deployment-manifests/manifests/backend-deployment.yml || { echo "Failed to apply backend-deployment.yml"; exit 1; }
          kubectl apply -f deployment-manifests/manifests/mongo-deployment.yml || { echo "Failed to apply mongo-deployment.yml"; exit 1; }

      - name: Verify deployment
        run: |
          kubectl get pods -n default
          kubectl get services -n default
          kubectl describe svc mern-frontend -n default
