name: Deploy MERN App
on:
  pull_request:
    branches: [main]
    types: [closed]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

  deploy:
    runs-on: ubuntu-22.04
    if: github.event.pull_request.merged == true 
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push frontend
      uses: docker/build-push-action@v3
      with:
        context: ./mern/frontend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/frontend:pr-${{ github.event.pull_request.number }}-${{ github.sha }}
    - name: Build and push backend
      uses: docker/build-push-action@v3
      with:
        context: ./mern/backend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/node-backend:pr-${{ github.event.pull_request.number }}-${{ github.sha }}
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: latest
    - name: Configure KUBECONFIG
      run: |
        echo "${{ secrets.KUBECONFIG }}" | base64 -d > $HOME/.kube/config
        chmod 600 $HOME/.kube/config
    - name: Create Kubernetes Secret
      run: |
        kubectl create secret generic backend-secrets \
          --from-literal=MONGODB_URI=${{ secrets.MONGODB_URI }} \
          --dry-run=client -o yaml | kubectl apply -f -
    - name: Decrypt deployment.yaml
      run: |
        echo "${{ secrets.DEPLOYMENT_YAML }}" | sops -d - > deployment.yaml
      env:
        SOPS_AGE_KEY: ${{ secrets.SOPS_AGE_KEY }}
    - name: Apply deployment
      run: kubectl apply -f deployment.yaml